# Generated by Django 4.1.7 on 2023-03-05 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityclasses',
            name='course_number',
            field=models.IntegerField(blank=True, default=2),
        ),
    ]
