# Generated by Django 4.1.7 on 2023-03-06 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0004_alter_universityclasses_course_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universityclasses',
            name='course_number',
        ),
    ]
