# Generated by Django 4.1.7 on 2023-03-05 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitycampus',
            name='course_number',
            field=models.IntegerField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='universitycampus',
            name='duration',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='universitycampus',
            name='instructor_name',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='universitycampus',
            name='title',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
