# Generated by Django 4.1.7 on 2023-03-05 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusApp', '0002_universitycampus_course_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universitycampus',
            old_name='course_number',
            new_name='campus_ID',
        ),
        migrations.RemoveField(
            model_name='universitycampus',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='universitycampus',
            name='instructor_name',
        ),
        migrations.AddField(
            model_name='universitycampus',
            name='state',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
